/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunnelRouteImport } from './routes/tunnel'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as TermsOfUseIndexRouteImport } from './routes/terms-of-use/index'
import { Route as PrivacyPolicyIndexRouteImport } from './routes/privacy-policy/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSentryExampleRouteImport } from './routes/api/sentry-example'
import { Route as AppAuthenticatedRouteImport } from './routes/_app/_authenticated'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppAuthenticatedProfileRouteImport } from './routes/_app/_authenticated/profile'
import { Route as AppAuthenticatedBillingRouteImport } from './routes/_app/_authenticated/billing'
import { Route as AppAdminAdminRouteImport } from './routes/_app/_admin/admin'

const TunnelRoute = TunnelRouteImport.update({
  id: '/tunnel',
  path: '/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseIndexRoute = TermsOfUseIndexRouteImport.update({
  id: '/terms-of-use/',
  path: '/terms-of-use/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyIndexRoute = PrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiSentryExampleRoute = ApiSentryExampleRouteImport.update({
  id: '/api/sentry-example',
  path: '/api/sentry-example',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthenticatedProfileRoute = AppAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedBillingRoute = AppAuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAdminAdminRoute = AppAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tunnel': typeof TunnelRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/pricing/': typeof PricingIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/terms-of-use/': typeof TermsOfUseIndexRoute
  '/admin': typeof AppAdminAdminRoute
  '/billing': typeof AppAuthenticatedBillingRoute
  '/profile': typeof AppAuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tunnel': typeof TunnelRoute
  '/': typeof AppIndexRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/pricing': typeof PricingIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/terms-of-use': typeof TermsOfUseIndexRoute
  '/admin': typeof AppAdminAdminRoute
  '/billing': typeof AppAuthenticatedBillingRoute
  '/profile': typeof AppAuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tunnel': typeof TunnelRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/_app/': typeof AppIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/terms-of-use/': typeof TermsOfUseIndexRoute
  '/_app/_admin/admin': typeof AppAdminAdminRoute
  '/_app/_authenticated/billing': typeof AppAuthenticatedBillingRoute
  '/_app/_authenticated/profile': typeof AppAuthenticatedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/sitemap.xml'
    | '/tunnel'
    | '/api/sentry-example'
    | '/pricing/'
    | '/privacy-policy/'
    | '/terms-of-use/'
    | '/admin'
    | '/billing'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/sitemap.xml'
    | '/tunnel'
    | '/'
    | '/api/sentry-example'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/admin'
    | '/billing'
    | '/profile'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/sitemap.xml'
    | '/tunnel'
    | '/_app/_admin'
    | '/_app/_authenticated'
    | '/api/sentry-example'
    | '/_app/'
    | '/pricing/'
    | '/privacy-policy/'
    | '/terms-of-use/'
    | '/_app/_admin/admin'
    | '/_app/_authenticated/billing'
    | '/_app/_authenticated/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TunnelRoute: typeof TunnelRoute
  ApiSentryExampleRoute: typeof ApiSentryExampleRoute
  PricingIndexRoute: typeof PricingIndexRoute
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  TermsOfUseIndexRoute: typeof TermsOfUseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunnel': {
      id: '/tunnel'
      path: '/tunnel'
      fullPath: '/tunnel'
      preLoaderRoute: typeof TunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use/': {
      id: '/terms-of-use/'
      path: '/terms-of-use'
      fullPath: '/terms-of-use/'
      preLoaderRoute: typeof TermsOfUseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof PrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/sentry-example': {
      id: '/api/sentry-example'
      path: '/api/sentry-example'
      fullPath: '/api/sentry-example'
      preLoaderRoute: typeof ApiSentryExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authenticated/profile': {
      id: '/_app/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthenticatedProfileRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_app/_authenticated/billing': {
      id: '/_app/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppAuthenticatedBillingRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_app/_admin/admin': {
      id: '/_app/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminAdminRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAdminRoute: typeof AppAdminAdminRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAdminRoute: AppAdminAdminRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedBillingRoute: typeof AppAuthenticatedBillingRoute
  AppAuthenticatedProfileRoute: typeof AppAuthenticatedProfileRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedBillingRoute: AppAuthenticatedBillingRoute,
  AppAuthenticatedProfileRoute: AppAuthenticatedProfileRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TunnelRoute: TunnelRoute,
  ApiSentryExampleRoute: ApiSentryExampleRoute,
  PricingIndexRoute: PricingIndexRoute,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  TermsOfUseIndexRoute: TermsOfUseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
